---
- name: Setup Python App
  hosts: all
  #roles:
  #  - geerlingguy.docker   
  vars:
    image_name: "{{ image_name }}"
    tag: "{{ tag }}"
  become: yes                 # Use become to execute tasks with sudo privileges
  tasks:
    - name: Install Docker on Ubuntu
      apt:
        name: docker
        state: present
      when: ansible_os_family == "Debian"
    - name: Install Docker on CentOS
      yum:
        name: docker
        state: present
      when: ansible_os_family == "RedHat"
    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install required packages for Docker Compose
      apt:
        name:
          - curl
          - python3-pip
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64
        dest: /usr/bin/docker-compose
        mode: 'u+x,g+x'
    - name: create a directory
      file:
          path: /opt/docker/bookkeeper
          state: directory
          recurse: yes
    - name: copy Docker-Compose
      template:
       src: "{{item.src}}"
       dest: "{{item.dest}}"
       backup: yes
      with_items:
       -  {src: docker-compose.yaml, dest: /opt/docker/bookkeeper/docker-compose.yaml}

    - name: start docker-compose
      shell: "docker-compose -f /opt/docker/bookkeeper/docker-compose.yaml up -d"
